# Site settings
title: Lahiru D. Chamain
name: Lahiru D. Chamain

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/chamain
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=cQAkxu4AAAAJ&hl=en
 - title: LinkedIn
   url: https://www.linkedin.com/in/lahiru-d-chamain/

#Any buzzword skills you want to include
skills:
 coding:
  - Python
  - C
  - C++
  - Matlab
 codecs:
  - JPEG
  - J2k
  - AVC/H.264
  - VVC/VTM-8.2
 deeplearning:
  - Pytorch
  - Tensorflow
  - keras
  - Image/video compression
  - End-to-end compression
 extras:
  - Unity
  - Online MP game developement
  - IoT

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Doctor of Philosophy (Ph.D.)
   start: 2021
   end: 2021
   employer: Electrical and Computer Engineering
   description: University of California, Davis
 - title: Research Intern
   start: 2020
   end: 2020
   employer: Interdigital Inc.
   description: Researched on Video Coding for Machines (VCM). Investigated an end-to-end design of the image/video compression codec optimized for a primary learning task (ex- detection) and the re-usability of the optimized codec for other secondary machine learning tasks such as classification and semantic segmentation. For the latter purpose, I proposed pre-trained connectors with  small number of parameters (81 max) to achieves significantly better rate-accuracy performance compared to the conventional codecs optimized for rate-distortion.
 - title: Master of Science (M.Sc.)
   start: 2020
   end: 2020
   employer: Electrical and Computer Engineering
   description: University of California, Davis
 - title: Lecturer on Contract
   start: 2017
   end: 2017
   employer: University of Moratuwa, Sri Lanka
   description: (Basic Electronics) Prepared lecture notes and supervised lab sessions 

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2016
   subject: Electroics and Telecommunication Engineering
   school: University of Moratuwa, Sri Lanka
 - level: Intern Software Engineer 
   date: 2015
   subject: CodeGen Pvt. Ltd., Sri Lanka
   school: Developed a Face recognition system with 93% accuracy using Harr wavelet features for the company use with Visual studio and OpenCV.


#This section is optional (as is the image link below)
coursera:
   profileurl: https://scholar.google.com/citations?user=cQAkxu4AAAAJ&hl=en
   courses:
    - title: Learning to group for image compression and classification
      link: https://github.com/chamain/Learning-to-group
      optionalimage: img/groupMain3.png
      date: 2021
    - title: VAE for image compression and classifications
      link: https://github.com/chamain/AE-classifier
      optionalimage: img/EncClassRec.png
      date: 2020
    - title: End-to-end image compression for multiple tasks
      link: https://arxiv.org/pdf/2011.06409.pdf
      optionalimage: img/multitask.png
      date: 2020
    - title: End-to-end compression for object detection
      link: https://arxiv.org/pdf/2011.06409.pdf
      optionalimage: img/cocoV4_4.png
      date: 2020
    - title: QuanNet
      link: https://ieeexplore.ieee.org/abstract/document/8784889
      optionalimage: img/quannet.png
      date: 2019
    - title: Wifius
      link: 
      optionalimage: img/wifius.png
      date: 2019
    - title: Faster J2k Classification
      link: https://arxiv.org/abs/1909.05638
      optionalimage: img/fasterj2k.png
      date: 2019
    - title: 3D reconstruction of buidings for oculus-rift
      link: https://drive.google.com/file/d/0BxTXVf2HbvGNSm1OeDU5bC1wMkE/view?usp=sharing
      optionalimage: img/3dreconjpg.jpg
      date: 2016
    - title: Brain Image Registration
      link: https://ieeexplore.ieee.org/abstract/document/7843407
      optionalimage: img/stitch.png
      date: 2016
      
# class projects      
classprojects:
   profileurl: https://scholar.google.com/citations?user=cQAkxu4AAAAJ&hl=en
   courses:
    - title: Image Completion challenge
      link: https://github.com/chamain/Learning-to-group
      optionalimage: 
      date: 2019
    - title: Kaggle fashion challenge
      link: https://github.com/chamain/AE-classifier
      optionalimage: 
      date: 2018
    - title: Brain image registration with contstrained optimization
      link: https://arxiv.org/pdf/2011.06409.pdf
      optionalimage: 
      date: 2019
 
#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - chamain/QuanNet
 - chamain/Faster-JPEG2000-classification
 - chamain/AE-classifier

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
 I'm a PhD candidate in Electrical & Computer Engineering at <b>University of California, Davis</b> supervised by Prof. Zhi Ding. This is my homepage.
intro2: |
 My research focus is bandwidth constrained End-to-end image/video compression with deep learninig. I'm passionate about computer vision, signal estimation and detection and internet of Things (IoT).
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
